import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.137.2:7080/realms/prospero/protocol/openid-connect/auth?response_type=code&client_id=rest-api-client&scope=openid%20profile%20email&state=wL0Xe8UNyfkltUlSgCf5k8Q0gow2p3YTe6_ONlP12SA%3D&redirect_uri=http://192.168.137.2:8800/login/oauth2/code/keycloak&nonce=hhbgLx6qbJMhnhyRDyj97qqArp6SW-4eZtOLXw2hc4s&code_challenge=RxpIV4TDVzGeRa6nbREoOldyYjD7rGF07BQ8qd6Im14&code_challenge_method=S256');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('admin');
  await page.getByRole('textbox', { name: 'Username or email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('a').filter({ hasText: 'Back Office' }).click();
  await page.locator('a').filter({ hasText: 'Foreign Exchange' }).click();
  await page.getByRole('link', { name: ' New Contract' }).click();
  await page.getByRole('combobox').first().selectOption('2: Object');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('star');
  await page.getByRole('cell', { name: 'IRON MAN' }).click();
  await page.getByRole('combobox').nth(1).selectOption('CHF');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('1500');
  await page.getByRole('combobox').nth(2).selectOption('USD');
  await page.locator('input[type="text"]').nth(2).click();
  await page.locator('input[type="text"]').nth(2).fill('%');
  await page.getByRole('cell', { name: '1010A01.CHF.0' }).click();
  await page.locator('input[type="text"]').nth(3).click();
  await page.locator('input[type="text"]').nth(3).fill('%');
  await page.getByRole('cell', { name: '1010A01.USD.0' }).click();
  await page.locator('input[type="text"]').nth(4).click();
  await page.locator('input[type="text"]').nth(4).fill('%');
  await page.getByRole('cell', { name: 'ROSS', exact: true }).click();
  await page.locator('input[type="text"]').nth(5).click();
  await page.locator('input[type="text"]').nth(5).fill('%');
  await page.getByRole('cell', { name: '1012A01.USD.0' }).click();
  await page.locator('.form-control.border-0.shadow-none.ng-untouched').click();
  await page.locator('.form-control.border-0.shadow-none.ng-untouched').fill('%');
  await page.getByRole('cell', { name: '1012A01.CHF.0' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: '  Spread Detail' }).first().click();
  await page.getByRole('button', { name: '  Charges' }).first().click();
});