name: Automated Playwright QA Run
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Runs automatically every day at 2:00 AM

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests & Report to AIO
        env:
          AIO_API_KEY: ${{ secrets.AIO_API_KEY }}
          JIRA_PAT: ${{ secrets.JIRA_PAT }}
        run: npx playwright test
